#write
import read

def update_quantity(laptop_dictionary):
    #laptop_dictionary = read.read_file()
    file = open("laptop.txt","w")

    for values in laptop_dictionary.values():
        file.write(str(values[0])+","+str(values[1])+","+str(values[2])+","+str(values[3])+","+str(values[4])+","+str(values[5]))
        file.write("\n")
    file.close()
    return file

def display_bill(name,phone_number,today_date_and_time,laptop_info,shipping_cost,grand_total):
    print("\n")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\t\t\t\t\t\t\t\t Invoice")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\t\t\t\t \t\t\t\tOur Electronics")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\n")
    print("\t\t\t\t Budanilkantha,Kathmandu | Contact No: 9862345600,9808029495")
    print("\n")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("The details of the laptop are:")
    print("----------------------------------------------------------------------------------------------------------------------------")
    print("Name of the customer:"+str(name))
    print("Contact number:"+str(phone_number))
    print("Date and time of purchase:"+str(today_date_and_time),)
    print("----------------------------------------------------------------------------------------------------------------------------")
    print("\n")
    print("Purchase Details are:")
    print("-----------------------------------------------------------------------------------------------------------------------------")
    print("Item Name \t\t Total Quantity \t\t Unit Price \t\t\tTotal")
    print("-----------------------------------------------------------------------------------------------------------------------------")
    for i, key in   enumerate(laptop_info):
        print(laptop_info[key][0],"\t\t\t",laptop_info[key][1],"\t\t\t",laptop_info[key][2],"\t\t\t","$",laptop_info[key][3])
    print("-----------------------------------------------------------------------------------------------------------------------------")
    print("Your Shipping cost is:", shipping_cost)
    print("Gross Amount: $"+ str(grand_total))
    print("Please note that the shipping cost is added in the grand total.")
    
def print_bill(name,phone_number,today_date_and_time,laptop_info,shipping_cost,grand_total):
    file_name = str(name) + "_" + str(today_date_and_time.strftime("%Y-%m-%d-%H-%M")) + ".txt"
    file = open(file_name,"w")
    file.write("\n")
    file.write("---------------------------------------------------------------------------------------------------------------------------")
    file.write("\t\t\t\t\t\t\t\t Invoice")
    file.write("---------------------------------------------------------------------------------------------------------------------------")
    file.write("\t\t\t\t \t\t\t\tOur Electronics")
    file.write("---------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("\t\t Budanilkantha,Kathmandu | Contact No: 9862345600,9808029495")
    file.write("\n")
    file.write("---------------------------------------------------------------------------------------------------------------------------")
    file.write("laptop details are:")
    file.write("----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("The details of the laptops are:")
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("Name of the customer:"+str(name))
    file.write("\n")
    file.write("Contact number:"+str(phone_number))
    file.write("\n")
    file.write("Date and time of purchase:"+str(today_date_and_time))
    file.write("\n")
    file.write("----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("Purchase Details are:")
    file.write("\n")
    file.write("-----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("Item Name \t\tTotal Quantity\t\t Unit Price \t\tTotal")
    file.write("\n")
    file.write("-----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    for i, key in   enumerate(laptop_info):
        file.write(str(laptop_info[key][0])+"\t\t\t"+str(laptop_info[key][1])+"\t\t\t"+str(laptop_info[key][2])+"\t\t\t"+"$"+str(laptop_info[key][3]))
        file.write("\n")
    file.write("-----------------------------------------------------------------------------------------------------------------------------")
    file.write("\n")
    file.write("Your Shipping cost is: "+str(shipping_cost))
    file.write("\n")
    file.write("Gross Amount: $"+ str(grand_total))
    file.write("\n")
    file.write("Note: Shipping Cost is added in the grand total.")
    file.close()

def display_purchase_bill(name_of_retailer,phone_number,today_date_and_time,laptop_info,VAT,grand_total):
    print("\n")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\t\t\t\t\t\t\t\t Invoice")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\t\t\t\t \t\t\t\tOur Electronics")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("\n")
    print("\t\t\t\t Budanilkantha,Kathmandu | Contact No: 9862345600,9808029495")
    print("\n")
    print("---------------------------------------------------------------------------------------------------------------------------")
    print("The details of the laptop are:")
    print("----------------------------------------------------------------------------------------------------------------------------")
    print("Name of the retailer     :"+ str(name_of_retailer))
    print("Contact number           :"+ str(phone_number) )
    print("Date and time of purchase: "+str(today_date_and_time),)
    print("----------------------------------------------------------------------------------------------------------------------------")
    print("\n")
    print("Purchase Details are:")
    print("-----------------------------------------------------------------------------------------------------------------------------")
    print("Item Name \t\t Total Quantity \t\t Unit Price \t\t\tTotal")
    print("-----------------------------------------------------------------------------------------------------------------------------")
    for i, key in   enumerate(laptop_info):
        print(laptop_info[key][0],"\t\t\t",laptop_info[key][1],"\t\t\t",laptop_info[key][2],"\t\t\t","$",laptop_info[key][3])
    print("-----------------------------------------------------------------------------------------------------------------------------")
    print("Your VAT cost is:", VAT)
    print("Grand Total: $"+ str(grand_total))
    
